### ISSUE TITLE
Youtube&Twitch Error

### ISSUE THREAD

**Issue by razor91111** [voidtemp/OpenXStreamLoader#3]
The program works great with chaturbate, but if you add a link to youtube or twitch to record broadcasts, an error appears in the favorites, as well as when you exit the program

![1](https://user-images.githubusercontent.com/66380989/93912963-1eb80500-fd0d-11ea-808c-e8843e6ea43a.JPG)
![2](https://user-images.githubusercontent.com/66380989/93912976-2081c880-fd0d-11ea-8a41-eedc139777b4.JPG)
[error.txt](https://github.com/voidtemp/OpenXStreamLoader/files/5262919/error.txt)

**Comment by voidtemp** [comment]
Sorry but SWF content is not supported.
Currently it's only c*bate.
In next releases xha**ive and str*at were planned.

Regarding exception: I guess (please copy all the text next time)
program was not able to save some XML element due to empty string. It uses room IDs as tags and for YT it didn't work.

**Comment by voidtemp** [comment]
Well maybe it will be not hard to add YT as major work is done by Streamlink. It's only channel name parsing and logo image extraction. But again this will be low priority.
Because as you might noticed this software is all about catching model being online.
